DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  credits INTEGER
);

CREATE TABLE location (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  latitude TEXT,
  longitude TEXT
)

CREATE TABLE vessel (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY (manager) REFERENCES user (id),
  FOREIGN KEY (box1) REFERENCES box (id),
  FOREIGN KEY (box2) REFERENCES box (id)
)

CREATE TABLE box (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  weight INTEGER,
  temp INTEGER,
  status INTEGER,
  closed_on DATETIME
)